name: macOS Build & Test

on: [push, pull_request]

env:
  xcodebuild: '/Applications/Xcode_12.app/Contents/Developer/usr/bin/xcodebuild'
  swift: '/Applications/Xcode_12.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift'

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Make xcodeproj
      run: ${swift} package generate-xcodeproj
    - name: Build
      run: ${xcodebuild}
    - name: Run tests
      run: ${xcodebuild} test -only-testing:RouterTests/EncoderTests -scheme Router-Package -sdk macosx11.0
